### PR TITLE
Cocos2d-x version updated to v3.11.1

### PR DESCRIPTION
**Pull request by AlwynC**
Updated the cocos2d-x version of the project from 3.8 to 3.11.1.
Project builds fine with the updated cocos2d-x version 3.11.1 on Xcode 7.3.
Integrated latest changes from the branch master also.

### CODE REVIEW

**Comment by AlwynC** [comment]
Hi @rauluranga I've updated the cocos2d-x version on the project to 3.11.1(latest cocos2d-x version).Please have a look.It works good without any modifications on FrameBuffer.cpp!

**Comment by rauluranga** [comment]
this is great!!
but if this is working, why the [issue](https://github.com/cocos2d/cocos2d-x/issues/13816) is still open??

**Comment by AlwynC** [comment]
@rauluranga The issue #13816 which you raised on cocos2d-x has been fixed in pull request #14471 on the cocos2d-x repository.They have not closed the issue as of now and have put it to unconfirmed milestone.Probably if future releases of cocos2d-x do not show up this issue again they may close it.You can check with the cocos2d-x devs about this.But as of latest cocos2d-x version 3.11.1 to which I've upgraded this framework to,the issue #13816 does not exist.

**Comment by AlwynC** [comment]
@rauluranga It is confirmed that issue #13816 has been fixed as of cocos2d-x version 3.11.1,hence it has been closed.

**Comment by rauluranga** [comment]
nice!
let me merge your pull request!

**Comment by rauluranga** [comment]
ummm when i try to compile the project, it throws the following error:

```
cpTransform.h file not found
/Cocos2dx-UIKit/cocos2d/cocos/physics/CCPhysicsWorld.cpp:30:10: In file included from /Cocos2dx-UIKit/cocos2d/cocos/physics/CCPhysicsWorld.cpp:30:
```

i've cleaned the project and deleted derived data.

**Comment by AlwynC** [comment]
@rauluranga It builds properly on my local after cleaning the project and deleting derived data.There are no errors at all.I will try to reproduce the issue you are facing and check what's gone wrong.

**Comment by AlwynC** [comment]
@rauluranga  I reproduced the issue you faced above and I've fixed it in my latest commit.Please check.

**Comment by rauluranga** [comment]
a bunch of files are still missing in your commit,
so, i just replaced the cocos2d folder with a newer one (from another cocos2dx project) and it seems to work, now compiles fine.

anyway your commits are merged now XD

thanks!

**Pull request closed without merging**
